2023-03-01 10:09:54,913:DEBUG:certbot._internal.main:certbot version: 2.0.0
2023-03-01 10:09:54,913:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-03-01 10:09:54,913:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'admin@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'devops-cloud.xyz']
2023-03-01 10:09:54,913:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-03-01 10:09:54,942:DEBUG:certbot._internal.log:Root logging level set at 30
2023-03-01 10:09:54,950:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-03-01 10:09:54,954:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f109a414250>
Prep: True
2023-03-01 10:09:54,959:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f109a414250> and installer None
2023-03-01 10:09:54,959:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-03-01 10:09:55,069:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/986645906', new_authzr_uri=None, terms_of_service=None), db32dc0389e9805f165958f95b31c5e4, Meta(creation_dt=datetime.datetime(2023, 2, 28, 13, 20, 30, tzinfo=<UTC>), creation_host='0c80db4bf90d', register_to_eff=None))>
2023-03-01 10:09:55,070:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-03-01 10:09:55,076:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-03-01 10:09:55,213:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 756
2023-03-01 10:09:55,214:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:09:55 GMT
Content-Type: application/json
Content-Length: 756
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "32KndSFdJbk": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/get/draft-ietf-acme-ari-00/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-03-01 10:09:55,216:INFO:certbot._internal.storage:Attempting to parse the version 2.2.0 renewal configuration file found at /etc/letsencrypt/renewal/carspot.live.conf with version 2.0.0 of Certbot. This might not work.
2023-03-01 10:09:55,231:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for devops-cloud.xyz
2023-03-01 10:09:55,234:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2023-03-01 10:09:55,242:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2023-03-01 10:09:55,247:DEBUG:acme.client:Requesting fresh nonce
2023-03-01 10:09:55,248:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-03-01 10:09:55,291:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-03-01 10:09:55,292:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:09:55 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 1AADhWm-te_pJQWUE2tZwTmVpnTSq-g0Z6ZcMOG63npEi-k
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-03-01 10:09:55,292:DEBUG:acme.client:Storing nonce: 1AADhWm-te_pJQWUE2tZwTmVpnTSq-g0Z6ZcMOG63npEi-k
2023-03-01 10:09:55,292:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "devops-cloud.xyz"\n    }\n  ]\n}'
2023-03-01 10:09:55,299:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjFBQURoV20tdGVfcEpRV1VFMnRad1RtVnBuVFNxLWcwWjZaY01PRzYzbnBFaS1rIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "MdgMmBCthxPZYzel6M7BeW0hVad-KsWFnXc0Z1EzqKqplXOjJJvvRYFRZ0libDfzxtgK3bCKCFN4UrMrF8EGDqGbxakfpzRUXrMSwSC8r9unTEy-Ber7QhzEOggfeyqctz0eYr5pA2p-geZ-ZYk4XrCfRScyXVnZdF9-x2XFtjvP157N-F6iK6x6pWtSvm0tmL8PZq2_37cWJ__wbhuzTAfBvhhjWUySEMIrfIGcgGcA4ycUDqPFziJEYxOJlAN7MfesTdRuo54yz7YdDtdWZEBYenp3kJEFFiwrIN0KO_-JIlYUwRKPRZuq0r6oPEAup2xeJRp4DUuH6RWspv9eyQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImRldm9wcy1jbG91ZC54eXoiCiAgICB9CiAgXQp9"
}
2023-03-01 10:09:55,480:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2023-03-01 10:09:55,481:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 01 Mar 2023 10:09:55 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/986645906/167549938996
Replay-Nonce: 15C9UGRJDA0k3IL0cPMK8cxMg53L7JdJKuLoT6-iBzs1HP4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2023-03-08T10:09:55Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "devops-cloud.xyz"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319062616"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/986645906/167549938996"
}
2023-03-01 10:09:55,481:DEBUG:acme.client:Storing nonce: 15C9UGRJDA0k3IL0cPMK8cxMg53L7JdJKuLoT6-iBzs1HP4
2023-03-01 10:09:55,481:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:09:55,483:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319062616:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjE1QzlVR1JKREEwazNJTDBjUE1LOGN4TWc1M0w3SmRKS3VMb1Q2LWlCenMxSFA0IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMTkwNjI2MTYifQ",
  "signature": "Z7itqlkQy2zAP0cogCvaUKngRThRPzNYFDbUXXXSJ0uNAQrqB9kJ9oydBv5JtYTUkK1f7l3uYO_ZT-mo3FNy-WezM7h6anX7DBEXp0gWx3K1tmirgdCmMAe6fBPCByQ2ftpWBsOrx9Q8NPjaIu1sGIWBWN4uGUayjD9eYRf1ykPZ0X_iw1lKSpEUbeKmvB5SwkZnfOX9YuE11n8BgwKVnBMZw1MSGkaaRPpCK0BnPVIhuRyQAde4pOXl-fshQetGhBafQrWXcXdp3U56uSwlZdBNGTnobAgxjZbFkXW7rfJfX3sFg05TcVa70NhBId7vV1Cujxhnqau27I9fJ5xsYQ",
  "payload": ""
}
2023-03-01 10:09:55,531:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207319062616 HTTP/1.1" 200 800
2023-03-01 10:09:55,532:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:09:55 GMT
Content-Type: application/json
Content-Length: 800
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 1AADGhyxMf88WbwYNz5Em57-Uj4bcaDVPF32SZ6mb307VoU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "pending",
  "expires": "2023-03-08T10:09:55Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Q_r0mw",
      "token": "OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Sv9rEw",
      "token": "OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/wI9wUw",
      "token": "OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI"
    }
  ]
}
2023-03-01 10:09:55,532:DEBUG:acme.client:Storing nonce: 1AADGhyxMf88WbwYNz5Em57-Uj4bcaDVPF32SZ6mb307VoU
2023-03-01 10:09:55,532:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-03-01 10:09:55,533:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:09:55,533:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2023-03-01 10:09:55,533:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2023-03-01 10:09:55,539:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI
2023-03-01 10:09:55,540:DEBUG:acme.client:JWS payload:
b'{}'
2023-03-01 10:09:55,542:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Q_r0mw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjFBQURHaHl4TWY4OFdid1lOejVFbTU3LVVqNGJjYURWUEYzMlNaNm1iMzA3Vm9VIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8yMDczMTkwNjI2MTYvUV9yMG13In0",
  "signature": "WzMMPID6ZGfQ7WvCpK74sqKQQ1OkT35biZENQm8KanI8Lmw6cNGRaFCxCH6fhzTNx8RVXyHeUAYFwUfeJT4w25PE2OgykD36qPkRl1ka5ZyPLSCkjNhSux5hhQyaDt7Aj43eLHkQHYiDXCTWTu6fSJCHQwAho0-vH8Ul24f7HKxG6CUU7OtC1hZOaTdeMQmy_haD5G0_ob8LsaE6_BeghSVGSB77Sw-xxARX3Tx_Q_08VYYzUv_watf6qAECGTQEz5XqHWpTQh4Gz7hXr5oREMpe57M9e0cKr_d1Xd13JPydMb6lXlUXNmlrDfOStW6i2U8yMKlvW3pDJqg_yH7gbw",
  "payload": "e30"
}
2023-03-01 10:09:55,594:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/207319062616/Q_r0mw HTTP/1.1" 200 187
2023-03-01 10:09:55,595:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:09:55 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319062616>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Q_r0mw
Replay-Nonce: C878uDUPx4wqvFDqvZRGuq22LO6n2XInDkIi1_T6N_dMztQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Q_r0mw",
  "token": "OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI"
}
2023-03-01 10:09:55,595:DEBUG:acme.client:Storing nonce: C878uDUPx4wqvFDqvZRGuq22LO6n2XInDkIi1_T6N_dMztQ
2023-03-01 10:09:55,596:INFO:certbot._internal.auth_handler:Waiting for verification...
2023-03-01 10:09:56,597:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:09:56,599:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319062616:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkM4Nzh1RFVQeDR3cXZGRHF2WlJHdXEyMkxPNm4yWEluRGtJaTFfVDZOX2RNenRRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMTkwNjI2MTYifQ",
  "signature": "M2eJVnZbfXNVTh0obx_0f0LwF7qodYZCV0BMEiVeI8zyeObuymBnB5131DN1QfxxTe4DdnQSE7g2V9VKeqMB-6XSyT71T_7CeptBa-KZhu5RLl4D5zO4Rbi7WH9xBgJG0kIY9uaUQGdF7uYjCv-SJS_5PZ08TO6XJi5zgcpuohOm8_hlWJ8Qikc1iL7fV63mlvhLzP0zSynqAxfqD7B-mFkmzNx9mmFfe9NRck5xayqn6K6dHEZpZd27Xp6zmA0_MC6Eyp1NX_jrsb_6qjeddQP6IZMWVeVV_o3wFZ2RbVie9poEJpAosHNsLHgYcJJAHSQu-ALgaXFa21SQTvrEPg",
  "payload": ""
}
2023-03-01 10:09:56,645:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207319062616 HTTP/1.1" 200 1233
2023-03-01 10:09:56,646:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:09:56 GMT
Content-Type: application/json
Content-Length: 1233
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 15C9S2LSuHpW1Br3xiifgjUI7M1VAU6NoaOw21NYGikjxvE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "invalid",
  "expires": "2023-03-08T10:09:55Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI: \"\u003c!doctype html\u003e\u003chtml lang=\\\"en\\\"\u003e\u003chead\u003e\u003cmeta http-equiv=\\\"content-type\\\" content=\\\"text/html;charset=utf-8\\\"/\u003e\u003cmeta name=\\\"viewport\\\" co\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319062616/Q_r0mw",
      "token": "OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI",
      "validationRecord": [
        {
          "url": "http://devops-cloud.xyz/.well-known/acme-challenge/OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI",
          "hostname": "devops-cloud.xyz",
          "port": "80",
          "addressesResolved": [
            "34.102.136.180"
          ],
          "addressUsed": "34.102.136.180"
        }
      ],
      "validated": "2023-03-01T10:09:55Z"
    }
  ]
}
2023-03-01 10:09:56,646:DEBUG:acme.client:Storing nonce: 15C9S2LSuHpW1Br3xiifgjUI7M1VAU6NoaOw21NYGikjxvE
2023-03-01 10:09:56,647:INFO:certbot._internal.auth_handler:Challenge failed for domain devops-cloud.xyz
2023-03-01 10:09:56,647:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:09:56,647:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: devops-cloud.xyz
  Type:   unauthorized
  Detail: 34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI: "<!doctype html><html lang=\"en\"><head><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\"/><meta name=\"viewport\" co"

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2023-03-01 10:09:56,648:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2023-03-01 10:09:56,648:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-03-01 10:09:56,648:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-03-01 10:09:56,649:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/OuLo1fPB_vVxs8dZvYMyiuYhisJ4US2pCxssxKNedkI
2023-03-01 10:09:56,649:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2023-03-01 10:09:56,649:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2023-03-01 10:09:56,657:ERROR:certbot._internal.log:Some challenges have failed.
