2023-03-01 10:12:33,938:DEBUG:certbot._internal.main:certbot version: 2.0.0
2023-03-01 10:12:33,942:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-03-01 10:12:33,943:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'admin@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'devops-cloud.xyz']
2023-03-01 10:12:33,943:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-03-01 10:12:33,976:DEBUG:certbot._internal.log:Root logging level set at 30
2023-03-01 10:12:33,979:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-03-01 10:12:33,988:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fc26d2f0280>
Prep: True
2023-03-01 10:12:33,989:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fc26d2f0280> and installer None
2023-03-01 10:12:33,989:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-03-01 10:12:34,105:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/986645906', new_authzr_uri=None, terms_of_service=None), db32dc0389e9805f165958f95b31c5e4, Meta(creation_dt=datetime.datetime(2023, 2, 28, 13, 20, 30, tzinfo=<UTC>), creation_host='0c80db4bf90d', register_to_eff=None))>
2023-03-01 10:12:34,106:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-03-01 10:12:34,115:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-03-01 10:12:34,247:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 756
2023-03-01 10:12:34,248:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:12:34 GMT
Content-Type: application/json
Content-Length: 756
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "U6_Xe0gUkMI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/get/draft-ietf-acme-ari-00/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-03-01 10:12:34,249:INFO:certbot._internal.storage:Attempting to parse the version 2.2.0 renewal configuration file found at /etc/letsencrypt/renewal/carspot.live.conf with version 2.0.0 of Certbot. This might not work.
2023-03-01 10:12:34,261:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for devops-cloud.xyz
2023-03-01 10:12:34,268:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2023-03-01 10:12:34,270:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2023-03-01 10:12:34,273:DEBUG:acme.client:Requesting fresh nonce
2023-03-01 10:12:34,274:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-03-01 10:12:34,318:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-03-01 10:12:34,319:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:12:34 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 1AADJjmABXkF044Gr3jVAHWDIpjkOH1Kd-sFJDZBmcroKgY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-03-01 10:12:34,319:DEBUG:acme.client:Storing nonce: 1AADJjmABXkF044Gr3jVAHWDIpjkOH1Kd-sFJDZBmcroKgY
2023-03-01 10:12:34,320:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "devops-cloud.xyz"\n    }\n  ]\n}'
2023-03-01 10:12:34,326:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjFBQURKam1BQlhrRjA0NEdyM2pWQUhXRElwamtPSDFLZC1zRkpEWkJtY3JvS2dZIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "JmFqcHS2XHft9D0wsWxUDo3vk6r4KB42dv0h4dfrmuztI8OW2ts8cwwY7NV8t45nY_XZk3oqOwrbYWPAgByMkGKArol6bRAONsBrQ2yyxfvW4KHe4RsHBKfeQ3eHxa5_qlrMMQ98qHs640Mt4pwXYMEM_BwpaPV00YFZQp4ZuuUTX9WG4JL8IrpcBCAjIvLRfJ1lgeglMPQOLjQqZEaPbR1Xd8aqxcucDF_IeiFkMnmX9N--67VFGwo4BE1O3wQ6PH7EJn-6vZwxRZaa5MIyCXI2aHR2JAaDwYeK-QdoKyD-1gg623wMmuzRupE67l562wdRutT2YhYFZQT6oXXaCQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImRldm9wcy1jbG91ZC54eXoiCiAgICB9CiAgXQp9"
}
2023-03-01 10:12:34,503:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2023-03-01 10:12:34,504:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 01 Mar 2023 10:12:34 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/986645906/167550307776
Replay-Nonce: 1AADjc1bxJz3BwNPzWYoVaEvSlb6IGdFrpoZRweGfL1CG0c
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2023-03-08T10:12:34Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "devops-cloud.xyz"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319563666"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/986645906/167550307776"
}
2023-03-01 10:12:34,504:DEBUG:acme.client:Storing nonce: 1AADjc1bxJz3BwNPzWYoVaEvSlb6IGdFrpoZRweGfL1CG0c
2023-03-01 10:12:34,505:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:12:34,509:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319563666:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjFBQURqYzFieEp6M0J3TlB6V1lvVmFFdlNsYjZJR2RGcnBvWlJ3ZUdmTDFDRzBjIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMTk1NjM2NjYifQ",
  "signature": "o6349gID62Am0sFmin7e4kLhWEJmvhc0qn7ASDPlr_qlBNe8TmsageylDntSSVuSH2f5hwc7bZaAnosBbfQckcTixh2-71rv2ZrJ9LFH0c2343MivRfkCmW7pr63o1olbLZkPNachwa1us3BLeb8yF-9Hbz8neyJcPwLsQJ5p5JqbIojqdzhqtUC2Iabl3WTCFl_1RI05Vos6lyxp9ev_rGNmW5_-2ZHaPkgqlhVrgjsh7WkERpiZx5wivmR2nD7vOgrzT_v_MXnSNP74feR00moUVyVTcB35pmDhS7ME3GWc61NdbxgJRNHnUwCIAoaBC5m0ilXE9uqDk4EhGzHjA",
  "payload": ""
}
2023-03-01 10:12:34,556:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207319563666 HTTP/1.1" 200 800
2023-03-01 10:12:34,557:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:12:34 GMT
Content-Type: application/json
Content-Length: 800
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: C878-MIQ3u64VWWBJy7KFN0-9OCsclaAlnCvxMw0MOuw-PY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "pending",
  "expires": "2023-03-08T10:12:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/bIGR_w",
      "token": "MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/yiHHGQ",
      "token": "MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/V9W13A",
      "token": "MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk"
    }
  ]
}
2023-03-01 10:12:34,557:DEBUG:acme.client:Storing nonce: C878-MIQ3u64VWWBJy7KFN0-9OCsclaAlnCvxMw0MOuw-PY
2023-03-01 10:12:34,558:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-03-01 10:12:34,558:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:12:34,558:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2023-03-01 10:12:34,558:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2023-03-01 10:12:34,560:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk
2023-03-01 10:12:34,560:DEBUG:acme.client:JWS payload:
b'{}'
2023-03-01 10:12:34,562:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/bIGR_w:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkM4NzgtTUlRM3U2NFZXV0JKeTdLRk4wLTlPQ3NjbGFBbG5DdnhNdzBNT3V3LVBZIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8yMDczMTk1NjM2NjYvYklHUl93In0",
  "signature": "pvlV9jHm7cZ5R_eF87GDWtQ1CzwACqX0sz5WfW8oVwzyjaqpPJ9BvGQ38c-_gpGXeVN6LMP_JG2gdFqa7mMxF6KoHOHjmA_7xG9Aw3VzruoSiLTkahZ2uXrqYCtX_PoCCiJLMlY_Gegs6bMjbs5YjtoAujuNMMOkdXNYBCtFwZLYJpigaDIbXNJnKaVOB10CO4F5ExDOM0aiVGiViol0T15ZJCjSjEDzz6L10N8uz6tQ-Z0vDBiK79SYbDv-5Wlv60OirwWHcHNgqdV7v6m3dYbPesVGnX96a9mlrCHTtGndLGGj_XSDnC6PezJ_pFl7QHw7vRDpvpFaL2QzkWCpng",
  "payload": "e30"
}
2023-03-01 10:12:34,616:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/207319563666/bIGR_w HTTP/1.1" 200 187
2023-03-01 10:12:34,617:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:12:34 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319563666>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/bIGR_w
Replay-Nonce: 1AADHSEZO2pouu2uMbney38T0PdXzYK7SeWg2I9gbApiaqU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/bIGR_w",
  "token": "MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk"
}
2023-03-01 10:12:34,618:DEBUG:acme.client:Storing nonce: 1AADHSEZO2pouu2uMbney38T0PdXzYK7SeWg2I9gbApiaqU
2023-03-01 10:12:34,618:INFO:certbot._internal.auth_handler:Waiting for verification...
2023-03-01 10:12:35,619:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:12:35,620:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207319563666:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIjFBQURIU0VaTzJwb3V1MnVNYm5leTM4VDBQZFh6WUs3U2VXZzJJOWdiQXBpYXFVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMTk1NjM2NjYifQ",
  "signature": "aAzoVsfVi2tXTgqENf5GY-7qs6aMTQ-eEZkIC_2RqR8xsgiFLGlifRtIvFGq_GXRHNq46wmGiS-chppX0skwZ0PxH_1GdRLBWaPrE_4gtCfahv39qr5lkrugDqcz4tpIznFkvChvO2oEQjxnfX-vU93ABTTyp5dyK1KnxyF9DfXy54UoLDCRlEyApiHw_b3IhunnSJM42SH5P9grdFJ-G72WduR4Z-jPM6wrogKYj-YRQErQwWTOI2crpb7BWQ579r79OfXjybsOZFi-VcCygkBt2XIzxug3Mz3bCcJRWHqaX8TmYELpfJiVyuyiUNyBGhMswjlu7pKzS0k9SJpOBA",
  "payload": ""
}
2023-03-01 10:12:35,666:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207319563666 HTTP/1.1" 200 1233
2023-03-01 10:12:35,667:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:12:35 GMT
Content-Type: application/json
Content-Length: 1233
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: C878cOjCZOOScgPKLk-jq42cOdxM_YWgeRk5igv8AYV6XVQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "invalid",
  "expires": "2023-03-08T10:12:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk: \"\u003c!doctype html\u003e\u003chtml lang=\\\"en\\\"\u003e\u003chead\u003e\u003cmeta http-equiv=\\\"content-type\\\" content=\\\"text/html;charset=utf-8\\\"/\u003e\u003cmeta name=\\\"viewport\\\" co\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207319563666/bIGR_w",
      "token": "MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk",
      "validationRecord": [
        {
          "url": "http://devops-cloud.xyz/.well-known/acme-challenge/MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk",
          "hostname": "devops-cloud.xyz",
          "port": "80",
          "addressesResolved": [
            "34.102.136.180"
          ],
          "addressUsed": "34.102.136.180"
        }
      ],
      "validated": "2023-03-01T10:12:34Z"
    }
  ]
}
2023-03-01 10:12:35,667:DEBUG:acme.client:Storing nonce: C878cOjCZOOScgPKLk-jq42cOdxM_YWgeRk5igv8AYV6XVQ
2023-03-01 10:12:35,668:INFO:certbot._internal.auth_handler:Challenge failed for domain devops-cloud.xyz
2023-03-01 10:12:35,668:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:12:35,668:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: devops-cloud.xyz
  Type:   unauthorized
  Detail: 34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk: "<!doctype html><html lang=\"en\"><head><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\"/><meta name=\"viewport\" co"

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2023-03-01 10:12:35,669:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2023-03-01 10:12:35,669:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-03-01 10:12:35,669:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-03-01 10:12:35,669:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/MbhULUXj_cOFB-WaRCl0gqFrGrDZF1myCclCTO6S5kk
2023-03-01 10:12:35,670:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2023-03-01 10:12:35,670:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2023-03-01 10:12:35,676:ERROR:certbot._internal.log:Some challenges have failed.
