2023-03-01 10:22:20,849:DEBUG:certbot._internal.main:certbot version: 2.0.0
2023-03-01 10:22:20,850:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-03-01 10:22:20,850:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'admin@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'devops-cloud.xyz']
2023-03-01 10:22:20,850:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-03-01 10:22:20,919:DEBUG:certbot._internal.log:Root logging level set at 30
2023-03-01 10:22:20,923:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-03-01 10:22:20,936:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f2c143a0a60>
Prep: True
2023-03-01 10:22:20,937:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f2c143a0a60> and installer None
2023-03-01 10:22:20,937:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-03-01 10:22:21,140:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/986645906', new_authzr_uri=None, terms_of_service=None), db32dc0389e9805f165958f95b31c5e4, Meta(creation_dt=datetime.datetime(2023, 2, 28, 13, 20, 30, tzinfo=<UTC>), creation_host='0c80db4bf90d', register_to_eff=None))>
2023-03-01 10:22:21,141:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-03-01 10:22:21,158:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-03-01 10:22:21,379:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 756
2023-03-01 10:22:21,380:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:22:21 GMT
Content-Type: application/json
Content-Length: 756
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "VFB-xWLX_nM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/get/draft-ietf-acme-ari-00/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-03-01 10:22:21,382:INFO:certbot._internal.storage:Attempting to parse the version 2.2.0 renewal configuration file found at /etc/letsencrypt/renewal/carspot.live.conf with version 2.0.0 of Certbot. This might not work.
2023-03-01 10:22:21,393:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for devops-cloud.xyz
2023-03-01 10:22:21,410:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0003_key-certbot.pem
2023-03-01 10:22:21,420:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0003_csr-certbot.pem
2023-03-01 10:22:21,422:DEBUG:acme.client:Requesting fresh nonce
2023-03-01 10:22:21,422:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-03-01 10:22:21,496:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-03-01 10:22:21,497:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:22:21 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: F977roItLWdjqOKBsxSAghLvBZ_AvDYBFH-vhKKB6FFrrEo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-03-01 10:22:21,497:DEBUG:acme.client:Storing nonce: F977roItLWdjqOKBsxSAghLvBZ_AvDYBFH-vhKKB6FFrrEo
2023-03-01 10:22:21,497:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "devops-cloud.xyz"\n    }\n  ]\n}'
2023-03-01 10:22:21,501:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkY5Nzdyb0l0TFdkanFPS0JzeFNBZ2hMdkJaX0F2RFlCRkgtdmhLS0I2RkZyckVvIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "LDtwkOzoegs3Kd6Twv-SrVZ_1tyu86UuVosZramNUYTu_qCQip4QLgYJC3HTJlDIn8MqtFyCMETG6GCpTeuLTZNmwQBdArAjB1ST8ogpbMe-oq9QI1MlYleGnJAnm1j6rdMJZaXtwWpmZKcXGJkGOaC3nPpjglWdDUUaL8ew5i8-1qhCCe-FUCai3OYbN7ioRQNmWvPS9HGXsJ_rF0u2444IKztc4tt96C4ns7RCSjKLFrb0hwitG4jIPbbSEyrAmBn3zukF8Rkc0OQECMLiYKP6ZhyPxCHCiuSdU9fbuZIMutKeQ2rhbeYfUEvcomPPX8-OTGU3VGU7IKrj41PB5Q",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImRldm9wcy1jbG91ZC54eXoiCiAgICB9CiAgXQp9"
}
2023-03-01 10:22:21,598:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2023-03-01 10:22:21,599:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 01 Mar 2023 10:22:21 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/986645906/167551559086
Replay-Nonce: A5FEMYaz99B3ofD4Z5NBvjVvApSArLOkKKKvKKD0IM8HYGg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2023-03-08T10:22:21Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "devops-cloud.xyz"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/207321290206"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/986645906/167551559086"
}
2023-03-01 10:22:21,599:DEBUG:acme.client:Storing nonce: A5FEMYaz99B3ofD4Z5NBvjVvApSArLOkKKKvKKD0IM8HYGg
2023-03-01 10:22:21,599:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:22:21,601:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207321290206:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkE1RkVNWWF6OTlCM29mRDRaNU5CdmpWdkFwU0FyTE9rS0tLdktLRDBJTThIWUdnIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMjEyOTAyMDYifQ",
  "signature": "NJwZLHqXK5uvWD6SNgI4YWSV7eNV4rJY8QH5rHbvWj5MOWH0joF6B6xmI2hAMyMhXCkZrbFFfYCRHSo6qR4ZVOoqxEXR3PNqC5FBci6o6m2PeG7bLhcv3aQYzESjO5_zUscCUfqk1v5DaNg-1M3BdwZu9kJzZr86ijF_3b5zmVJ34OvEqTt14cpwYRVju7b-8rpLWeGgbK7I7qsU0VKEzBgfc_1roRtuGbqtXYzSqGqQFCSSQbouTg4SxIGRurqXEluW2PDw294zh3C7rz_z-Mr02z88UlWaxZGwDk_h-56ywFxruMZBPwUvTzoDPVKtIXw1I6cY9ZEAVcgfaGipRg",
  "payload": ""
}
2023-03-01 10:22:21,673:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207321290206 HTTP/1.1" 200 800
2023-03-01 10:22:21,674:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:22:21 GMT
Content-Type: application/json
Content-Length: 800
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: A5FEEvL3uqphTUHZjj3cn37HMeyhHD3xPP8TxZrIoVSa7hA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "pending",
  "expires": "2023-03-08T10:22:21Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/jMe_Xw",
      "token": "ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/DV8Esw",
      "token": "ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/5wPiog",
      "token": "ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo"
    }
  ]
}
2023-03-01 10:22:21,674:DEBUG:acme.client:Storing nonce: A5FEEvL3uqphTUHZjj3cn37HMeyhHD3xPP8TxZrIoVSa7hA
2023-03-01 10:22:21,675:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-03-01 10:22:21,675:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:22:21,675:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2023-03-01 10:22:21,675:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2023-03-01 10:22:21,679:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo
2023-03-01 10:22:21,679:DEBUG:acme.client:JWS payload:
b'{}'
2023-03-01 10:22:21,681:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/jMe_Xw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkE1RkVFdkwzdXFwaFRVSFpqajNjbjM3SE1leWhIRDN4UFA4VHhacklvVlNhN2hBIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8yMDczMjEyOTAyMDYvak1lX1h3In0",
  "signature": "Lklt3EmhqfdujtbAQG6sCqeKQ4zd-eAYfN2747eyv5x_BXVAgLOLZN6eV6zcMzZxQ6dwHlB8akQ1Ye_pupDXkl6zspzFYlwAWeI2Md8ww7gUVg1zlZNqlA06-WsE73aP_txj-kTlwBIvqRlV2lzBrNM795C0uG62a-Q88iCbVbNk9x7WzNJpjI0SdV6Ln4EhrqEgG-wZy8Ko3Evn29z3q3CeLM0aePYahhq83sRU8b1WFZfZSjzrglhPDY4hDwC1K14rXdeeicaWVjfwe33iZqgRZrHD2ckfnShRbW-fBTqbntPxmUqLERUJT0LsulZ_f8pwCpazTH_avfaCAszlHw",
  "payload": "e30"
}
2023-03-01 10:22:21,770:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/207321290206/jMe_Xw HTTP/1.1" 200 187
2023-03-01 10:22:21,771:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:22:21 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/207321290206>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/jMe_Xw
Replay-Nonce: F70E0dUq7l_dbwuxBpYAO49H24bPTEbrfFY2mQLz4kYcQGU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/jMe_Xw",
  "token": "ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo"
}
2023-03-01 10:22:21,771:DEBUG:acme.client:Storing nonce: F70E0dUq7l_dbwuxBpYAO49H24bPTEbrfFY2mQLz4kYcQGU
2023-03-01 10:22:21,772:INFO:certbot._internal.auth_handler:Waiting for verification...
2023-03-01 10:22:22,776:DEBUG:acme.client:JWS payload:
b''
2023-03-01 10:22:22,778:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/207321290206:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTg2NjQ1OTA2IiwgIm5vbmNlIjogIkY3MEUwZFVxN2xfZGJ3dXhCcFlBTzQ5SDI0YlBURWJyZkZZMm1RTHo0a1ljUUdVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8yMDczMjEyOTAyMDYifQ",
  "signature": "I8O9WqFik6gl2ViijOMFWLixrYcWwBiC9A4FPnjqiI5iFCfjq94mtT1AmDI6jIFKZi0HrokxYYnXhsvVHpXNI68JUSbfBraOrUr3V51c_ktevM55hOGPC0enyquWn1FpNIZW_Qt_e_2R0aDjJJ1rJzZ96tkEgtmba23BFnY_9tbjxDHxfB76UMzIpnzld_lXQXe4ThCnKIMZIyd6bdFXfTDaW3-O0hPELEHSkLjfZnvg-9sjoMU_5idhih3RTiNoioljEgTtUItwlBSnjHPifLEFTPhUTdYIh48j0RtK_QZK_kfMUXnVldDcd9XUO6WZ6LZ3eLJ-caTxGD5ahxj5TQ",
  "payload": ""
}
2023-03-01 10:22:22,859:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/207321290206 HTTP/1.1" 200 1233
2023-03-01 10:22:22,861:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 01 Mar 2023 10:22:22 GMT
Content-Type: application/json
Content-Length: 1233
Connection: keep-alive
Boulder-Requester: 986645906
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: F70EHGsXiKnSi7t4b05If9zGrL-dP9CPl1ywvWF65SaNCSI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "devops-cloud.xyz"
  },
  "status": "invalid",
  "expires": "2023-03-08T10:22:21Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo: \"\u003c!doctype html\u003e\u003chtml lang=\\\"en\\\"\u003e\u003chead\u003e\u003cmeta http-equiv=\\\"content-type\\\" content=\\\"text/html;charset=utf-8\\\"/\u003e\u003cmeta name=\\\"viewport\\\" co\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/207321290206/jMe_Xw",
      "token": "ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo",
      "validationRecord": [
        {
          "url": "http://devops-cloud.xyz/.well-known/acme-challenge/ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo",
          "hostname": "devops-cloud.xyz",
          "port": "80",
          "addressesResolved": [
            "34.102.136.180"
          ],
          "addressUsed": "34.102.136.180"
        }
      ],
      "validated": "2023-03-01T10:22:21Z"
    }
  ]
}
2023-03-01 10:22:22,862:DEBUG:acme.client:Storing nonce: F70EHGsXiKnSi7t4b05If9zGrL-dP9CPl1ywvWF65SaNCSI
2023-03-01 10:22:22,873:INFO:certbot._internal.auth_handler:Challenge failed for domain devops-cloud.xyz
2023-03-01 10:22:22,877:INFO:certbot._internal.auth_handler:http-01 challenge for devops-cloud.xyz
2023-03-01 10:22:22,877:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: devops-cloud.xyz
  Type:   unauthorized
  Detail: 34.102.136.180: Invalid response from http://devops-cloud.xyz/.well-known/acme-challenge/ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo: "<!doctype html><html lang=\"en\"><head><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\"/><meta name=\"viewport\" co"

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2023-03-01 10:22:22,879:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2023-03-01 10:22:22,879:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-03-01 10:22:22,879:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-03-01 10:22:22,879:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/ZfWYoWpNf0W9TQAP0PdsFpHlMZ876Tszv2YDtAXIcEo
2023-03-01 10:22:22,880:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2023-03-01 10:22:22,880:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2023-03-01 10:22:22,882:ERROR:certbot._internal.log:Some challenges have failed.
